spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/training-microservices-2020-04/konfigurasi
          default-label: master
          search-paths: '{application}'