server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/endymuhardin/belajar-spring-cloud-config-konfigurasi.git
          default-label: main
          search-paths: '{application}'